[project]
name = "demo"
requires-python = ">=3.10"
dependencies = ["requests>=2.31"]

[project.optional-dependencies]
test = ["pytest==8.4.2"]

[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.package-dir]
"" = "src"
